# Generated by Django 3.1.5 on 2021-02-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210210_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinfo',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.country'),
        ),
    ]
