# Generated by Django 3.1.5 on 2021-02-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210210_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryReport',
            new_name='DateReport',
        ),
    ]
