# Generated by Django 3.1.5 on 2021-02-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210212_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.country')),
                ('confirmed', models.IntegerField()),
                ('confirmed_new', models.IntegerField()),
                ('confirmed_pct_change', models.FloatField()),
                ('confirmed_rank_region', models.IntegerField()),
                ('confirmed_rank_world', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('deaths_new', models.IntegerField()),
                ('deaths_pct_change', models.FloatField()),
                ('deaths_rank_region', models.IntegerField()),
                ('deaths_rank_world', models.IntegerField()),
                ('recovered', models.IntegerField(default=0)),
                ('recovered_new', models.IntegerField()),
                ('recovered_pct_change', models.FloatField()),
                ('recovered_rank_region', models.IntegerField()),
                ('recovered_rank_world', models.IntegerField()),
                ('active', models.IntegerField(default=0)),
                ('active_new', models.IntegerField()),
                ('active_pct_change', models.FloatField()),
                ('active_rank_region', models.IntegerField()),
                ('active_rank_world', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datereport',
            name='country',
        ),
        migrations.AddField(
            model_name='datereport',
            name='country',
            field=models.ManyToManyField(to='report.Country'),
        ),
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('country', models.ManyToManyField(to='report.Country')),
            ],
        ),
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('country', models.ManyToManyField(to='report.Country')),
            ],
        ),
    ]
