# Generated by Django 3.1.5 on 2021-02-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20210215_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='date',
            field=models.CharField(default='not available', max_length=10),
        ),
    ]
