# Generated by Django 3.1.5 on 2021-02-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_statusreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='date',
            field=models.CharField(default='undefined', max_length=10),
        ),
    ]
