# Generated by Django 3.1.5 on 2021-02-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210217_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusReport',
        ),
    ]
