# Generated by Django 3.1.5 on 2021-02-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_delete_statusreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.country')),
                ('date', models.CharField(default='undefined', max_length=10)),
                ('confirmed', models.IntegerField()),
                ('confirmed_new', models.IntegerField()),
                ('confirmed_pct_change', models.FloatField()),
                ('confirmed_rank_region', models.IntegerField()),
                ('confirmed_rank_world', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('deaths_new', models.IntegerField()),
                ('deaths_pct_change', models.FloatField()),
                ('deaths_rank_region', models.IntegerField()),
                ('deaths_rank_world', models.IntegerField()),
                ('recovered', models.IntegerField(default=0)),
                ('recovered_new', models.IntegerField()),
                ('recovered_pct_change', models.FloatField()),
                ('recovered_rank_region', models.IntegerField()),
                ('recovered_rank_world', models.IntegerField()),
                ('active', models.IntegerField(default=0)),
                ('active_new', models.IntegerField()),
                ('active_pct_change', models.FloatField()),
                ('active_rank_region', models.IntegerField()),
                ('active_rank_world', models.IntegerField()),
            ],
        ),
    ]
