# Generated by Django 3.1.5 on 2021-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_statusreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryinfo',
            name='internet_code',
            field=models.CharField(default='br', max_length=2),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='map_image',
            field=models.CharField(default='www.google.com', max_length=264),
        ),
    ]
