# Generated by Django 3.1.5 on 2021-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20210218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinfo',
            name='map_image',
            field=models.URLField(default='www.google.com', max_length=264),
        ),
    ]
