# Generated by Django 3.1.5 on 2021-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20210218_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='active_new_rank_region',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='active_new_rank_world',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_new_rank_region',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_new_rank_world',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_new_rank_region',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_new_rank_world',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='recovered_new_rank_region',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='recovered_new_rank_world',
            field=models.IntegerField(default=0),
        ),
    ]
