# Generated by Django 3.1.5 on 2021-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20210219_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='date',
            field=models.CharField(default='undefined', max_length=22),
        ),
    ]
