# Generated by Django 3.1.5 on 2021-03-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20210220_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='datereport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='statusreport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='weekreport',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CountryInfo',
        ),
        migrations.DeleteModel(
            name='DateReport',
        ),
        migrations.DeleteModel(
            name='MonthReport',
        ),
        migrations.DeleteModel(
            name='StatusReport',
        ),
        migrations.DeleteModel(
            name='WeekReport',
        ),
    ]
