# Generated by Django 3.1.5 on 2021-03-02 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_statusreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 2)),
        ),
    ]
