# Generated by Django 3.1.5 on 2021-03-02 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20210302_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
