# Generated by Django 3.1.5 on 2021-03-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20210302_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='active_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='mortality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='mortality_rank_region',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='mortality_rank_world',
            field=models.IntegerField(default=1000),
        ),
    ]
