# Generated by Django 3.1.5 on 2021-03-03 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20210302_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('month_str', models.CharField(max_length=8)),
                ('confirmed', models.IntegerField(default=0)),
                ('confirmed_new', models.IntegerField(default=0)),
                ('confirmed_pct_change', models.FloatField(default=0)),
                ('confirmed_rank_region', models.IntegerField(default=0)),
                ('confirmed_rank_world', models.IntegerField(default=0)),
                ('confirmed_new_rank_region', models.IntegerField(default=0)),
                ('confirmed_new_rank_world', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('deaths_new', models.IntegerField(default=0)),
                ('deaths_pct_change', models.FloatField(default=0)),
                ('deaths_rank_region', models.IntegerField(default=0)),
                ('deaths_rank_world', models.IntegerField(default=0)),
                ('deaths_new_rank_region', models.IntegerField(default=0)),
                ('deaths_new_rank_world', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('recovered_new', models.IntegerField(default=0)),
                ('recovered_pct_change', models.FloatField(default=0)),
                ('recovered_rank_region', models.IntegerField(default=0)),
                ('recovered_rank_world', models.IntegerField(default=0)),
                ('recovered_new_rank_region', models.IntegerField(default=0)),
                ('recovered_new_rank_world', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('active_new', models.IntegerField(default=0)),
                ('active_pct', models.FloatField(default=0)),
                ('active_pct_change', models.FloatField(default=0)),
                ('active_rank_region', models.IntegerField(default=0)),
                ('active_rank_world', models.IntegerField(default=0)),
                ('active_new_rank_region', models.IntegerField(default=0)),
                ('active_new_rank_world', models.IntegerField(default=0)),
                ('mortality', models.FloatField(default=0)),
                ('mortality_rank_region', models.IntegerField(default=1000)),
                ('mortality_rank_world', models.IntegerField(default=1000)),
                ('country', models.ManyToManyField(to='report.Country')),
            ],
        ),
    ]
