# Generated by Django 3.1.5 on 2021-03-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_monthreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthreport',
            name='active',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='active_new',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='active_new_rank_region',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='active_new_rank_world',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='active_pct',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='active_pct_change',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='active_rank_region',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='active_rank_world',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='confirmed_new',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='confirmed_new_rank_region',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='confirmed_new_rank_world',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='deaths_new',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='deaths_new_rank_region',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='deaths_new_rank_world',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='month_str',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='mortality',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='mortality_rank_region',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='mortality_rank_world',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='recovered',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='recovered_new',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='recovered_new_rank_region',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='recovered_new_rank_world',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='recovered_pct_change',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='recovered_rank_region',
        ),
        migrations.RemoveField(
            model_name='monthreport',
            name='recovered_rank_world',
        ),
        migrations.AddField(
            model_name='monthreport',
            name='month',
            field=models.CharField(default='2000-01', max_length=7),
        ),
    ]
