# Generated by Django 3.1.5 on 2021-03-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20210304_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthreport',
            name='country',
        ),
        migrations.AddField(
            model_name='monthreport',
            name='country',
            field=models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.CASCADE, to='report.country'),
        ),
    ]
