# Generated by Django 3.1.5 on 2021-03-09 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_auto_20210304_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthreport',
            name='days_in_month',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='monthreport',
            name='update',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
