# Generated by Django 3.1.5 on 2021-03-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_auto_20210309_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthreport',
            old_name='update',
            new_name='last_update',
        ),
    ]
