# Generated by Django 3.1.5 on 2021-03-17 23:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_auto_20210309_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='2000-01', max_length=7)),
                ('confirmed', models.IntegerField(default=0)),
                ('confirmed_pct_change', models.FloatField(default=0)),
                ('confirmed_rank_region', models.IntegerField(default=0)),
                ('confirmed_rank_world', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('deaths_pct_change', models.FloatField(default=0)),
                ('deaths_rank_region', models.IntegerField(default=0)),
                ('deaths_rank_world', models.IntegerField(default=0)),
                ('last_update', models.DateField(default=datetime.date.today)),
                ('country', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.CASCADE, to='report.country')),
            ],
        ),
    ]
