# Generated by Django 3.1.5 on 2021-03-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_weekreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='db_update',
            field=models.CharField(default='2021-1-1', max_length=8),
        ),
    ]
