# Generated by Django 3.1.5 on 2021-03-21 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_statusreport_db_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='db_update',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
