# Generated by Django 3.1.5 on 2021-03-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_auto_20210321_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_new_pct_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_new_pct_change',
            field=models.FloatField(default=0),
        ),
    ]
