# Generated by Django 3.1.5 on 2021-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_auto_20210321_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='confirmed_new_pct_change',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='deaths_new_pct_change',
            field=models.FloatField(default=100),
        ),
    ]
