# Generated by Django 3.1.5 on 2021-03-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_configreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configreport',
            name='file_path',
            field=models.FilePathField(default='C:\\Users\\user\\Documents\\GitHub\\COVID-19'),
        ),
    ]
