# Generated by Django 3.1.5 on 2021-03-22 00:43

from django.db import migrations, models
import nt


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0032_auto_20210321_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configreport',
            name='file_path',
            field=models.FilePathField(path=nt.getcwd),
        ),
    ]
