# Generated by Django 3.1.5 on 2021-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_auto_20210321_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='mortality_quartile',
            field=models.CharField(default='4th quartile (very high mortality)', max_length=35),
        ),
    ]
