# Generated by Django 3.1.5 on 2021-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_statusreport_mortality_quartile'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='mortality_quartile_position',
            field=models.FloatField(default=50.0),
        ),
    ]
