# Generated by Django 3.1.5 on 2021-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0035_statusreport_mortality_quartile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNData',
            fields=[
                ('country', models.CharField(default='undefined', max_length=60, primary_key=True, serialize=False)),
                ('iso_code', models.CharField(default='AA', max_length=3)),
                ('year', models.CharField(default='2020', max_length=4)),
                ('population', models.IntegerField(default=10000000000.0)),
                ('density', models.FloatField(default=1.0)),
                ('population_male', models.IntegerField(default=10000000000.0)),
                ('population_female', models.IntegerField(default=10000000000.0)),
                ('sex_ratio', models.FloatField(default=1.0)),
                ('pct_minus_fourteen', models.IntegerField(default=10000000000.0)),
                ('pct_plus_sixty', models.IntegerField(default=10000000000.0)),
            ],
        ),
    ]
