# Generated by Django 3.1.5 on 2021-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_auto_20210402_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOCodeData',
            fields=[
                ('geoip_name', models.CharField(default='undefined', max_length=60, primary_key=True, serialize=False)),
                ('iso_code', models.CharField(default='AA', max_length=3)),
                ('un_name', models.CharField(default=models.CharField(default='undefined', max_length=60, primary_key=True, serialize=False), max_length=60)),
                ('country_name', models.CharField(default=models.CharField(default='undefined', max_length=60, primary_key=True, serialize=False), max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='undata',
            name='iso_code',
        ),
    ]
