# Generated by Django 3.1.5 on 2021-04-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0038_auto_20210402_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isocodedata',
            name='country_name',
            field=models.CharField(default=models.CharField(default='undefined', max_length=60), max_length=60),
        ),
        migrations.AlterField(
            model_name='isocodedata',
            name='geoip_name',
            field=models.CharField(default='undefined', max_length=60),
        ),
        migrations.AlterField(
            model_name='isocodedata',
            name='iso_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='isocodedata',
            name='un_name',
            field=models.CharField(default=models.CharField(default='undefined', max_length=60), max_length=60),
        ),
    ]
