# Generated by Django 3.1.5 on 2021-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0039_auto_20210402_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isocodedata',
            name='country_name',
            field=models.CharField(default='undefined', max_length=60),
        ),
        migrations.AlterField(
            model_name='isocodedata',
            name='un_name',
            field=models.CharField(default='undefined', max_length=60),
        ),
    ]
