# Generated by Django 3.1.5 on 2021-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0042_auto_20210404_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='isocodedata',
            name='geoname_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='isocodedata',
            name='iso_code',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
