# Generated by Django 3.1.5 on 2021-04-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0043_auto_20210404_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusReport',
        ),
    ]
