# Generated by Django 3.1.5 on 2021-04-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0045_statusreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='active_long_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='active_medium_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='active_short_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_long_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_medium_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_short_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_long_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_medium_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_short_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='recovered_long_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='recovered_medium_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='recovered_short_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
