# Generated by Django 3.1.5 on 2021-04-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0046_auto_20210410_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusreport',
            old_name='active_long_avg',
            new_name='active_new_long_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='active_medium_avg',
            new_name='active_new_medium_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='active_short_avg',
            new_name='active_new_short_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='confirmed_long_avg',
            new_name='confirmed_new_long_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='confirmed_medium_avg',
            new_name='confirmed_new_medium_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='confirmed_short_avg',
            new_name='confirmed_new_short_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='deaths_long_avg',
            new_name='deaths_new_long_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='deaths_medium_avg',
            new_name='deaths_new_medium_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='deaths_short_avg',
            new_name='deaths_new_short_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='recovered_long_avg',
            new_name='recovered_new_long_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='recovered_medium_avg',
            new_name='recovered_new_medium_avg',
        ),
        migrations.RenameField(
            model_name='statusreport',
            old_name='recovered_short_avg',
            new_name='recovered_new_short_avg',
        ),
    ]
