# Generated by Django 3.1.5 on 2021-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0047_auto_20210410_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configreport',
            name='db_delete',
        ),
        migrations.RemoveField(
            model_name='configreport',
            name='db_reload',
        ),
        migrations.RemoveField(
            model_name='configreport',
            name='db_update',
        ),
        migrations.AddField(
            model_name='configreport',
            name='task',
            field=models.IntegerField(choices=[('delete', 0), ('update', 1), ('reload', 2)], default=1),
        ),
    ]
