# Generated by Django 3.1.5 on 2021-04-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0048_auto_20210411_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configreport',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='configreport',
            name='file_path',
            field=models.FilePathField(path='C:\\Users\\user\\Documents\\GitHub\\COVID-19\\consolidated_data'),
        ),
        migrations.AlterField(
            model_name='configreport',
            name='task',
            field=models.IntegerField(choices=[(0, 'delete'), (1, 'update'), (2, 'reload')], default=1),
        ),
    ]
