# Generated by Django 3.1.5 on 2021-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0050_auto_20210411_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configreport',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
