# Generated by Django 3.1.5 on 2021-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0051_auto_20210411_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='configreport',
            name='auto_exec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configreport',
            name='var_name',
            field=models.CharField(default='dbconfig_', max_length=30, primary_key=True, serialize=False),
        ),
    ]
