# Generated by Django 3.1.5 on 2021-04-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0054_auto_20210411_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configreport',
            name='aux_file',
        ),
    ]
