# Generated by Django 3.1.5 on 2021-04-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0055_remove_configreport_aux_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigReport',
        ),
    ]
