# Generated by Django 3.1.5 on 2021-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0056_delete_configreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigReport',
            fields=[
                ('var_name', models.CharField(default='dbconfig_', max_length=30, primary_key=True, serialize=False)),
                ('base_file', models.FilePathField(path='C:\\Users\\user\\Documents\\GitHub\\COVID-19\\consolidated_data')),
                ('aux_file', models.FilePathField(path='C:\\Users\\user\\Documents\\GitHub\\COVID-19\\consolidated_data')),
                ('aux_file_two', models.FilePathField(path='C:\\Users\\user\\Documents\\GitHub\\COVID-19\\consolidated_data')),
                ('date', models.DateTimeField(auto_now=True)),
                ('task', models.IntegerField(choices=[(0, 'delete'), (1, 'update'), (2, 'reload')], default=1)),
                ('confirm_delete', models.BooleanField(default=True)),
                ('auto_exec', models.BooleanField(default=True)),
            ],
        ),
    ]
