# Generated by Django 3.1.5 on 2021-04-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0057_configreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configreport',
            old_name='aux_file',
            new_name='aux_file_one',
        ),
    ]
