# Generated by Django 3.1.5 on 2021-04-11 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0058_auto_20210411_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
