# Generated by Django 3.1.5 on 2021-04-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0059_auto_20210411_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configreport',
            name='date',
            field=models.CharField(default='not specified', max_length=60),
        ),
    ]
