# Generated by Django 3.1.5 on 2021-04-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0060_auto_20210411_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigReport',
        ),
    ]
