# Generated by Django 3.1.5 on 2021-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0062_configreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_new_by_hundreds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_new_by_hundreds_rank_world',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_new_by_hundreds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_new_by_hundreds_rank_world',
            field=models.IntegerField(default=1),
        ),
    ]
