# Generated by Django 3.1.5 on 2021-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0063_auto_20210418_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_by_hundreds_quartile',
            field=models.CharField(default='4th quartile (very high confirmed/100k)', max_length=40),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='confirmed_by_hundreds_quartile_position',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_by_hundreds_quartile',
            field=models.CharField(default='4th quartile (very high deaths/100k)', max_length=40),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='deaths_by_hundreds_quartile_position',
            field=models.FloatField(default=50.0),
        ),
    ]
