# Generated by Django 3.1.5 on 2021-05-10 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0064_auto_20210422_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('confirmed', models.IntegerField(default=0)),
                ('confirmed_new', models.IntegerField(default=0)),
                ('confirmed_new_short_avg', models.IntegerField(default=0)),
                ('confirmed_new_medium_avg', models.IntegerField(default=0)),
                ('confirmed_new_long_avg', models.IntegerField(default=0)),
                ('confirmed_by_hundreds', models.IntegerField(default=0)),
                ('confirmed_new_by_hundreds', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('deaths_new', models.IntegerField(default=0)),
                ('deaths_new_short_avg', models.IntegerField(default=0)),
                ('deaths_new_medium_avg', models.IntegerField(default=0)),
                ('deaths_new_long_avg', models.IntegerField(default=0)),
                ('deaths_by_hundreds', models.IntegerField(default=0)),
                ('deaths_new_by_hundreds', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('active_new', models.IntegerField()),
                ('active_by_hundreds', models.IntegerField(default=1)),
                ('active_pct', models.FloatField(default=0)),
                ('mortality', models.FloatField(default=0)),
                ('country', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.CASCADE, to='report.country')),
            ],
        ),
    ]
